searchd {
    listen = 0.0.0.0:9306:mysql41
    listen = 0.0.0.0:9308:http
    log = /var/log/manticore/searchd.log
    query_log = /var/log/manticore/query.log
    pid_file = /var/run/manticore/searchd.pid
    # binlog_path = /var/lib/manticore/binlog   # закомментировано для dev
}

index orders_idx {
    type = rt
    path = /var/lib/manticore/orders_idx
    rt_field = text
    rt_attr_uint = order_id
    rt_attr_string = number
    rt_attr_string = email
    rt_attr_string = client_name
    rt_attr_timestamp = create_date
}

indexer {
    mem_limit = 256M
}

common {
    plugin_dir = /usr/local/lib/manticore
    lemmatizer_base = /usr/share/manticore/
}